# Change these first
owner: KristianBQA 
repo: benqservers 
user-agent: KristianBQA 
sites:
  - name: BenQ AMS
    url: https://ams.benq.com/#/
  - name: BenQ IAM
    url: https://iam.benq.com/
  - name: BenQ DMS
    url: https://dms.benq.com/#/
  - name: BenQ X-Sign Broadcast
    url: https://x-signbroadcast.benq.com/
  - name: BenQ Service Portal
    url: https://service-portal.benq.com/login

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  
  baseUrl: /benqservers
  logoUrl: https://github.com/KristianBQA/benqservers/blob/af74e13081406ea2c8bb6511f253d3678af3faca/assets/BenQ%20Education%20logo%20White%20on%20teal.jpg
  name: BenQ Servers North America
  introTitle: BenQ North America
  introMessage: See the status of the BenQ servers in North America
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
